name: Auto Pull Request

on:
  push:
    branches:
      - '*'

jobs:
  auto_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Existing Pull Request for Current Branch
        id: check_pr
        run: |
          BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
          PR_EXISTS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/pulls?state=open" | jq -r --arg BRANCH "$BRANCH_NAME" '.[] | select(.head.ref == $BRANCH) | .html_url')

          if [ -n "$PR_EXISTS" ]; then
            echo "Pull Request already exists for branch $BRANCH_NAME: $PR_EXISTS"
            echo "::set-output name=pr_exists::true"
          else
            echo "::set-output name=pr_exists::false"
          fi

      - name: Stop Workflow if PR Exists
        if: steps.check_pr.outputs.pr_exists == 'true'
        run: exit 1

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          title: Automatically created pull request
          commit-message: Automatic pull request creation
          base: main

      - name: Notify pull request creation (Optional)
        if: steps.create_pr.outputs.pull_request_url
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: repo,message,commit,author,action,eventName,ref,workflow
          custom_payload: |
            {
              "text": "Pull request created: *{{ steps.create_pr.outputs.pull_request_url }}*"
            }
