name: Convert card to issue with labels

on:
  # Trigger the workflow when a card is converted to an issue
  issues:
    types: [converted]

jobs:
  add-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            // Get the priority and estimate from the card title
            const title = context.issue.title;
            const priorityMatch = title.match(/priority: (.*)/);
            const estimateMatch = title.match(/estimate: (\d+)(?:(h|d|w))?/);

            let priorityLabel = "";
            if (priorityMatch) {
              priorityLabel = priorityMatch[1];
            }

            let estimateLabel = "";
            if (estimateMatch) {
              const estimate = estimateMatch[1];
              const unit = estimateMatch[2];

              if (unit === "h") {
                estimateLabel = `${estimate} hours`;
              } else if (unit === "d") {
                estimateLabel = `${estimate} days`;
              } else if (unit === "w") {
                estimateLabel = `${estimate} weeks`;
              }
            }

            // Add labels to the issue
            core.addLabels(context.issue.number, [priorityLabel, estimateLabel]);
